# Generated by Django 5.1 on 2024-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز'},
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='محصولات', to='product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='محصولات', to='product.size'),
        ),
    ]
