# Generated by Django 5.1 on 2024-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_information_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products_img'),
        ),
    ]
