# Generated by Django 5.1 on 2024-08-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_image_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='نام عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products_img/', verbose_name='عکس کالا'),
        ),
    ]
