# Generated by Django 5.1 on 2024-09-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_brand_category_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
