# Generated by Django 5.1 on 2024-09-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='pictur',
        ),
    ]
